# @oanhnn on GitHub
dist: trusty
sudo: false
language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_ARGS

script:
  - bin/phpunit

after_success:
  - travis_retry composer require php-coveralls/php-coveralls
  - travis_retry bin/php-coveralls --coverage_clover=coverage/clover.xml -v